M48
; DRILL file {KiCad 8.0.6} date 2024-10-29T20:24:03-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-29T20:24:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0591
%
G90
G05
T1
X1.01Y-1.1663
X1.01Y-1.245
X1.01Y-1.3237
T2
X1.79Y-1.185
X1.79Y-1.3228
T3
X1.255Y-0.9974
X1.63Y-0.995
X1.79Y-0.995
M30
